# Generated by Django 4.1.3 on 2022-11-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("status", models.IntegerField(default=0)),
                ("addTime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectId", models.IntegerField()),
                ("number", models.IntegerField()),
                ("name", models.CharField(max_length=32)),
                ("step", models.IntegerField(default=0)),
                ("type", models.IntegerField(default=0)),
                ("status", models.IntegerField(default=0)),
                ("addTime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="task_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskId", models.IntegerField()),
                ("userId", models.IntegerField()),
                ("step", models.IntegerField()),
                ("addTime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("passWord", models.CharField(max_length=64)),
                ("age", models.IntegerField(default=2)),
                ("username", models.CharField(max_length=32)),
                ("addTime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Project_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addTime", models.DateTimeField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectApp.project",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectApp.userinfo",
                    ),
                ),
            ],
        ),
    ]
