# Generated by Django 4.1.3 on 2022-11-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0002_project_userrelation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project_userrelation", old_name="project", new_name="projectId",
        ),
    ]
