# Generated by Django 4.1.3 on 2022-11-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0003_rename_project_project_userrelation_projectid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task_user",
            name="taskId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projectApp.task"
            ),
        ),
        migrations.AlterField(
            model_name="task_user",
            name="userId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projectApp.userinfo"
            ),
        ),
    ]
