# Generated by Django 4.1.3 on 2022-11-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=100)),
                ("addTime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
